# The URL the site will be built for
base_url = "https://blueberrywren.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_feeds = true

author = "Blueberry Wren"

title="Blueberry Wren Thoughts"
description="The bloggings of Wren"
default_language="en"

[markdown]
bottom_footnotes = true

[markdown.highlighting]
# Whether to do syntax highlighting
highlight_code = true
# Theme can be a single theme...
theme = "monokai"
# ...or split into light/dark variants instead, e.g.:
# light_theme = "monokai"
# dark_theme = "monokai"

# Once you add Isabelle support:
# extra_grammars = ["extra/isabelle.tmLanguage.json"]

[extra]
# Put all your custom variables here
